/* automatically generated from kind-dialogs.glade */
#ifdef __SUNPRO_C
#pragma align 4 (kind_dialog_ui)
#endif
#ifdef __GNUC__
static const char kind_dialog_ui[] __attribute__ ((__aligned__ (4))) =
#else
static const char kind_dialog_ui[] =
#endif
{
  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><interface><requires lib=\"gt"
  "k+\" version=\"3.20\"/><requires lib=\"libxfce4ui-2\" version=\"4.11\"/"
  "><object class=\"XfceTitledDialog\" id=\"dialog\"><property name=\"can-"
  "focus\">False</property><property name=\"title\" translatable=\"yes\">K"
  "ind Panel Plugin</property><property name=\"default-width\">350</proper"
  "ty><property name=\"default-height\">200</property><property name=\"hid"
  "e-titlebar-when-maximized\">True</property><property name=\"icon-name\""
  ">gtk-properties</property><property name=\"type-hint\">normal</property"
  "><child internal-child=\"vbox\"><object class=\"GtkBox\" id=\"dialog-vb"
  "ox2\"><property name=\"visible\">True</property><property name=\"can-fo"
  "cus\">False</property><property name=\"orientation\">vertical</property"
  "><property name=\"spacing\">2</property><child internal-child=\"action_"
  "area\"><object class=\"GtkButtonBox\" id=\"dialog-action_area2\"><prope"
  "rty name=\"visible\">True</property><property name=\"can-focus\">False<"
  "/property><property name=\"layout-style\">end</property><child><object "
  "class=\"GtkButton\" id=\"close-button\"><property name=\"label\">gtk-cl"
  "ose</property><property name=\"visible\">True</property><property name="
  "\"can-focus\">True</property><property name=\"receives-default\">True</"
  "property><property name=\"use-stock\">True</property></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">False"
  "</property><property name=\"position\">0</property></packing></child><c"
  "hild><object class=\"GtkButton\" id=\"help-button\"><property name=\"la"
  "bel\">gtk-help</property><property name=\"visible\">True</property><pro"
  "perty name=\"can-focus\">True</property><property name=\"receives-defau"
  "lt\">True</property><property name=\"use-stock\">True</property></objec"
  "t><packing><property name=\"expand\">False</property><property name=\"f"
  "ill\">False</property><property name=\"position\">1</property><property"
  " name=\"secondary\">True</property></packing></child></object><packing>"
  "<property name=\"expand\">False</property><property name=\"fill\">True<"
  "/property><property name=\"pack-type\">end</property><property name=\"p"
  "osition\">0</property></packing></child><child><object class=\"GtkFrame"
  "\" id=\"frame1\"><property name=\"visible\">True</property><property na"
  "me=\"can-focus\">False</property><property name=\"label-xalign\">0.0399"
  "99999105930328</property><property name=\"shadow-type\">none</property>"
  "<child><object class=\"GtkAlignment\"><property name=\"visible\">True</"
  "property><property name=\"can-focus\">False</property><property name=\""
  "top-padding\">7</property><property name=\"left-padding\">13</property>"
  "<child><object class=\"GtkBox\" id=\"vbox1\"><property name=\"visible\""
  ">True</property><property name=\"can-focus\">False</property><property "
  "name=\"orientation\">vertical</property><property name=\"spacing\">7</p"
  "roperty><child><object class=\"GtkBox\" id=\"caps_lock_box\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"spacing\">7</property><child><object class=\"Gtk"
  "Switch\" id=\"caps_lock_show\"><property name=\"visible\">True</propert"
  "y><property name=\"can-focus\">True</property><property name=\"active\""
  ">True</property></object><packing><property name=\"expand\">False</prop"
  "erty><property name=\"fill\">True</property><property name=\"position\""
  ">0</property></packing></child><child><object class=\"GtkLabel\" id=\"c"
  "aps_lock_switch_label\"><property name=\"visible\">True</property><prop"
  "erty name=\"can-focus\">False</property><property name=\"label\" transl"
  "atable=\"yes\">Show Caps Lock Indicator</property></object><packing><pr"
  "operty name=\"expand\">False</property><property name=\"fill\">True</pr"
  "operty><property name=\"position\">1</property></packing></child></obje"
  "ct><packing><property name=\"expand\">False</property><property name=\""
  "fill\">True</property><property name=\"position\">0</property></packing"
  "></child><child><object class=\"GtkBox\" id=\"num_lock_box\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"spacing\">7</property><child><object class=\"Gtk"
  "Switch\" id=\"num_lock_show\"><property name=\"visible\">True</property"
  "><property name=\"can-focus\">True</property><property name=\"active\">"
  "True</property></object><packing><property name=\"expand\">False</prope"
  "rty><property name=\"fill\">True</property><property name=\"position\">"
  "0</property></packing></child><child><object class=\"GtkLabel\" id=\"nu"
  "m_lock_switch_label\"><property name=\"visible\">True</property><proper"
  "ty name=\"can-focus\">False</property><property name=\"label\" translat"
  "able=\"yes\">Show Num Lock Indicator</property></object><packing><prope"
  "rty name=\"expand\">False</property><property name=\"fill\">True</prope"
  "rty><property name=\"position\">1</property></packing></child></object>"
  "<packing><property name=\"expand\">False</property><property name=\"fil"
  "l\">True</property><property name=\"position\">1</property></packing></"
  "child><child><object class=\"GtkBox\" id=\"scroll_lock_box\"><property "
  "name=\"visible\">True</property><property name=\"can-focus\">False</pro"
  "perty><property name=\"spacing\">7</property><child><object class=\"Gtk"
  "Switch\" id=\"scroll_lock_show\"><property name=\"visible\">True</prope"
  "rty><property name=\"can-focus\">True</property><property name=\"active"
  "\">True</property></object><packing><property name=\"expand\">False</pr"
  "operty><property name=\"fill\">True</property><property name=\"position"
  "\">0</property></packing></child><child><object class=\"GtkLabel\" id=\""
  "scroll_lock_switch_label\"><property name=\"visible\">True</property><p"
  "roperty name=\"can-focus\">False</property><property name=\"label\" tra"
  "nslatable=\"yes\">Show Scroll Lock Indicator</property></object><packin"
  "g><property name=\"expand\">False</property><property name=\"fill\">Tru"
  "e</property><property name=\"position\">1</property></packing></child><"
  "/object><packing><property name=\"expand\">False</property><property na"
  "me=\"fill\">True</property><property name=\"position\">2</property></pa"
  "cking></child></object></child></object></child><child type=\"label\"><"
  "object class=\"GtkLabel\" id=\"toggle_indicators\"><property name=\"vis"
  "ible\">True</property><property name=\"can-focus\">False</property><pro"
  "perty name=\"label\" translatable=\"yes\">Toggle Indicator</property><a"
  "ttributes><attribute name=\"weight\" value=\"bold\"/></attributes></obj"
  "ect></child></object><packing><property name=\"expand\">True</property>"
  "<property name=\"fill\">True</property><property name=\"position\">1</p"
  "roperty></packing></child></object></child><action-widgets><action-widg"
  "et response=\"0\">close-button</action-widget><action-widget response=\""
  "0\">help-button</action-widget></action-widgets></object><object class="
  "\"GtkListStore\" id=\"liststore1\"><columns><column type=\"GdkPixbuf\"/"
  "><column type=\"gchararray\"/><column type=\"gchararray\"/><column type"
  "=\"gboolean\"/></columns></object></interface>"
};

static const unsigned kind_dialog_ui_length = 6603u;

